(in-package #:blackboard-protocol/tests)

;;; Wave-1 done-when: a mock coding-agent KS (no LLM, no MCP) runs
;;; edit → requeue → test → requeue → done on the KSAR loop.

(defclass mock-compute (compute-capability)
  ((runs :initform nil :accessor mock-runs)
   (result :initarg :result :initform '(:exit 0) :accessor mock-result)))

(defmethod run-command ((cap mock-compute) argv &key)
  (push argv (mock-runs cap))
  (mock-result cap))

(defclass mock-edit (code-editing-capability)
  ((files :initform (make-hash-table :test 'equal) :accessor mock-files)))

(defmethod read-file ((cap mock-edit) path &key)
  (gethash path (mock-files cap)))

(defmethod write-file ((cap mock-edit) path content &key)
  (setf (gethash path (mock-files cap)) content)
  path)

(defun install-coding-caps (bb &key (edit (make-instance 'mock-edit))
                                    (compute (make-instance 'mock-compute)))
  (register-capability bb edit)
  (register-capability bb compute)
  (values edit compute))

(defun coding-handler (board ksar)
  "One KSAR = one step. Continue via requeue-ksar, never a trigger-key flicker."
  (when (eq :cancelled (workspace-status (ksar-workspace ksar)))
    (return-from coding-handler nil))
  (let* ((phase (read-section board :phase :default :edit))
         (edit (get-capability board :code-editing))
         (compute (get-capability board :compute))
         (log (read-section board :trace :default nil)))
    (write-section board :trace (append log (list phase)))
    (ecase phase
      (:edit
       (invoke-operation edit 'write-file "src/foo.lisp" "(defun foo () :ok)")
       (write-section board :phase :test)
       (requeue-ksar board ksar))
      (:test
       (invoke-operation compute 'run-command '("rove" "foo"))
       (write-section board :phase :done)
       (requeue-ksar board ksar))
      (:done
       (write-section board :status :completed)))))

(defun start-coding-workspace (bb name &key around)
  (let ((ws (fork-workspace bb name)))
    (watch (workspace-blackboard ws) :id (intern (format nil "KS-~A" name))
           :requires '(:pending-task)
           :handler (if around (funcall around #'coding-handler) #'coding-handler))
    ws))

(deftest mock-coding-agent-edit-test-done
  (let* ((bb (make-blackboard))
         (edit nil)
         (compute nil)
         (ws (start-coding-workspace bb "job-1")))
    (multiple-value-setq (edit compute) (install-coding-caps bb))
    (write-section (workspace-blackboard ws) :pending-task '(:fix "foo"))
    (drain bb)
    (ok (equal '(:edit :test :done)
               (read-section (workspace-blackboard ws) :trace)))
    (ok (eq :completed (read-section (workspace-blackboard ws) :status)))
    (ok (equal "(defun foo () :ok)"
               (gethash "src/foo.lisp" (mock-files edit))))
    (ok (equal '(("rove" "foo")) (reverse (mock-runs compute))))
    (ok (eq :absent (read-section bb :phase :default :absent))
        "phases stay on the workspace")))

(deftest mock-coding-agent-steps-are-serial
  (let* ((bb (make-blackboard :max-concurrency 4))
         (ws (start-coding-workspace bb "serial-job"))
         (overlap nil)
         (running 0)
         (lock (%test-lock "overlap")))
    (install-coding-caps bb)
    (watch (workspace-blackboard ws) :id 'probe :requires '(:phase)
           :handler (lambda (board ksar)
                      (declare (ignore board ksar))
                      (bt2:with-lock-held (lock)
                        (incf running)
                        (when (> running 1)
                          (setf overlap t)))
                      (sleep 0.03)
                      (bt2:with-lock-held (lock)
                        (decf running))))
    (write-section (workspace-blackboard ws) :pending-task t)
    (drain bb)
    (ng overlap "coding-agent steps never overlap on one workspace")))

(deftest second-workspace-interleaves
  (let* ((bb (make-blackboard :max-concurrency 2))
         (log (event-log))
         (gate (make-barrier 2)))
    (flet ((wrap (name)
             (lambda (inner)
               (lambda (board ksar)
                 (when (eq :edit (read-section board :phase :default :edit))
                   (log-event log :start name)
                   (arrive gate)
                   (log-event log :end name))
                 (funcall inner board ksar)))))
      (let ((a (start-coding-workspace bb "job-a" :around (wrap :a)))
            (b (start-coding-workspace bb "job-b" :around (wrap :b))))
        (install-coding-caps bb)
        (write-section (workspace-blackboard a) :pending-task t)
        (write-section (workspace-blackboard b) :pending-task t)
        (drain bb)
        (let ((starts (subseq (events log) 0 2)))
          (ok (equal '(:start :start) (mapcar #'first starts))
              "two coding workspaces start in parallel"))
        (ok (equal '(:edit :test :done)
                   (read-section (workspace-blackboard a) :trace)))
        (ok (equal '(:edit :test :done)
                   (read-section (workspace-blackboard b) :trace)))))))

(deftest coding-agent-cancel-sticks
  (let* ((bb (make-blackboard))
         (ws (fork-workspace bb "cancel-job"))
         (steps 0))
    (install-coding-caps bb)
    (watch (workspace-blackboard ws) :id 'ks :requires '(:pending-task)
           :handler (lambda (board ksar)
                      (incf steps)
                      (cancel-workspace ws)
                      (coding-handler board ksar)))
    (write-section (workspace-blackboard ws) :pending-task t)
    (drain bb)
    (ok (= 1 steps))
    (ok (eq :cancelled (workspace-status ws)))
    (ok (null (read-section (workspace-blackboard ws) :trace :default nil))
        "cancelled workspace does not run remaining coding steps")
    (ok (eq :absent (read-section (workspace-blackboard ws) :status
                                 :default :absent)))))

(deftest coding-agent-discard-and-merge
  (let* ((bb (make-blackboard))
         (keep (start-coding-workspace bb "keep"))
         (drop (start-coding-workspace bb "drop")))
    (install-coding-caps bb)
    (write-section (workspace-blackboard keep) :pending-task t)
    (write-section (workspace-blackboard drop) :pending-task t)
    (drain bb)
    (discard-workspace drop)
    (ok (null (get-workspace bb "drop")))
    (merge-workspace keep :strategy :overwrite)
    (ok (eq :completed (read-section bb :status)))
    (ok (equal '(:edit :test :done) (read-section bb :trace)))))

(deftest nested-reviewer-child
  (let* ((bb (make-blackboard))
         (parent (fork-workspace bb "author"))
         (review nil)
         (parent-saw nil))
    (install-coding-caps bb)
    (watch (workspace-blackboard parent) :id 'author :requires '(:pending-task)
           :handler (lambda (board ksar)
                      (declare (ignore ksar))
                      (setf review (fork-workspace board "reviewer" :parent parent))
                      (watch (workspace-blackboard review) :id 'review
                             :requires '(:draft)
                             :handler (lambda (child ksar2)
                                        (declare (ignore ksar2))
                                        (write-section child :ks-result :lgtm)
                                        (write-section child :status :completed)
                                        (merge-workspace review :strategy :overwrite)))
                      (write-section (workspace-blackboard review)
                                     :draft (read-section board :pending-task))
                      (write-section board :phase :await-review)))
    (watch (workspace-blackboard parent) :id 'parent-inbox :requires '(:ks-result)
           :handler (lambda (board ksar)
                      (declare (ignore ksar))
                      (setf parent-saw (read-section board :ks-result))))
    (write-section (workspace-blackboard parent) :pending-task "patch")
    (drain bb)
    (ok (eq :lgtm parent-saw)
        "child merge publishes :ks-result onto parent, firing the parent watcher")
    (ok (eq :lgtm (read-section (workspace-blackboard parent) :ks-result)))
    (ok (eq :completed (workspace-status review)))))
