(in-package #:blackboard-protocol/tests)

(deftest agenda-priority-fifo
  (let ((bb (make-blackboard :max-concurrency 1))
        (order nil))
    (watch bb :id 'low :requires '(:go) :priority 1
           :handler (lambda (board ksar)
                      (declare (ignore board ksar))
                      (push :low order)))
    (watch bb :id 'high-a :requires '(:go) :priority 10
           :handler (lambda (board ksar)
                      (declare (ignore board ksar))
                      (push :high-a order)))
    (watch bb :id 'high-b :requires '(:go) :priority 10
           :handler (lambda (board ksar)
                      (declare (ignore board ksar))
                      (push :high-b order)))
    (write-section bb :go t)
    (drain bb)
    (ok (equal '(:high-a :high-b :low) (reverse order))
        "higher priority first; equal priority is FIFO")))

(deftest serial-per-workspace
  (let* ((bb (make-blackboard :max-concurrency 4))
         (ws (fork-workspace bb "serial"))
         (log (event-log))
         (running 0)
         (overlap nil)
         (lock (bt2:make-lock)))
    (watch (workspace-blackboard ws) :id 'steps :requires '(:go)
           :handler (lambda (board ksar)
                      (bt2:with-lock-held (lock)
                        (incf running)
                        (when (> running 1)
                          (setf overlap t)))
                      (log-event log :start)
                      (sleep 0.05)
                      (log-event log :end)
                      (bt2:with-lock-held (lock)
                        (decf running))
                      (let ((n (read-section board :n :default 0)))
                        (write-section board :n (1+ n))
                        (when (< n 1)
                          (requeue-ksar board ksar)))))
    (write-section (workspace-blackboard ws) :go t)
    (drain bb)
    (ok (equal '(:start :end :start :end) (events log)))
    (ok (eql 2 (read-section (workspace-blackboard ws) :n)))
    (ng overlap "two KSARs of the same workspace never overlap")))

(deftest global-concurrency-interleaves-workspaces
  (let* ((bb (make-blackboard :max-concurrency 2))
         (a (fork-workspace bb "a"))
         (b (fork-workspace bb "b"))
         (log (event-log))
         (gate (make-barrier 2)))
    (flet ((handler (name)
             (lambda (board ksar)
               (declare (ignore board ksar))
               (log-event log :start name)
               (arrive gate)
               (log-event log :end name))))
      (watch (workspace-blackboard a) :id 'a :requires '(:go)
             :handler (handler :a))
      (watch (workspace-blackboard b) :id 'b :requires '(:go)
             :handler (handler :b)))
    (write-section (workspace-blackboard a) :go t)
    (write-section (workspace-blackboard b) :go t)
    (drain bb)
    (let ((ev (events log)))
      (ok (equal '(:start :start) (subseq (mapcar #'first ev) 0 2))
          "two workspaces start before either finishes when max-concurrency is 2")
      (ok (member :a (mapcar #'second ev)))
      (ok (member :b (mapcar #'second ev))))))

(deftest requeue-continues-same-workspace
  (let* ((bb (make-blackboard))
         (ws (fork-workspace bb "loop"))
         (boards nil)
         (steps 0))
    (watch (workspace-blackboard ws) :id 'agent :requires '(:n)
           :handler (lambda (board ksar)
                      (push board boards)
                      (incf steps)
                      (let ((n (read-section board :n)))
                        (write-section board :n (1+ n))
                        (when (< n 3)
                          (requeue-ksar board ksar)))))
    (write-section (workspace-blackboard ws) :n 1)
    (drain bb)
    (ok (= 3 steps))
    (ok (eql 4 (read-section (workspace-blackboard ws) :n)))
    (ok (every (lambda (b) (eq b (workspace-blackboard ws))) boards)
        "requeue does not bounce through a root trigger key")
    (ok (eq :absent (read-section bb :n :default :absent)))))

(deftest cancel-stops-requeue-and-pending
  (let* ((bb (make-blackboard))
         (ws (fork-workspace bb "stop"))
         (steps 0))
    (watch (workspace-blackboard ws) :id 'loop :requires '(:go)
           :handler (lambda (board ksar)
                      (incf steps)
                      (write-section board :ran t)
                      (cancel-workspace ws :reason "budget")
                      (requeue-ksar board ksar)))
    (write-section (workspace-blackboard ws) :go t)
    (drain bb)
    (ok (= 1 steps))
    (ok (eq :cancelled (workspace-status ws)))
    (ok (eq t (read-section (workspace-blackboard ws) :ran)))
    (ok (zerop (agenda-size bb)) "requeue after cancel is a no-op")))

(deftest cancel-skips-queued-ksar
  (let* ((bb (make-blackboard :max-concurrency 1))
         (ws (fork-workspace bb "skip"))
         (ran nil))
    (watch (workspace-blackboard ws) :id 'later :requires '(:go)
           :handler (lambda (board ksar)
                      (declare (ignore board ksar))
                      (setf ran t)))
    (write-section (workspace-blackboard ws) :go t)
    (cancel-workspace ws)
    (drain bb)
    (ng ran "queued KSAR for a cancelled workspace is not executed")))

(deftest max-steps-blocks-requeue
  (let* ((bb (make-blackboard))
         (ws (fork-workspace bb "budget" :max-steps 2))
         (steps 0))
    (watch (workspace-blackboard ws) :id 'loop :requires '(:go)
           :handler (lambda (board ksar)
                      (incf steps)
                      (requeue-ksar board ksar)))
    (write-section (workspace-blackboard ws) :go t)
    (drain bb)
    (ok (= 2 steps))
    (ok (= 2 (workspace-step-count ws)))))

(deftest handler-error-is-recorded-loop-lives
  (let ((bb (make-blackboard))
        (ok-ran nil))
    (watch bb :id 'boom :requires '(:x) :priority 10
           :handler (lambda (board ksar)
                      (declare (ignore board ksar))
                      (error "explode")))
    (watch bb :id 'ok :requires '(:x) :priority 1
           :handler (lambda (board ksar)
                      (declare (ignore board ksar))
                      (setf ok-ran t)))
    (write-section bb :x t)
    (drain bb)
    (ok ok-ran "later KSAR still runs after a handler error")
    (ok (consp (read-section bb :errors)))))

(deftest ksar-carries-handler-not-root-lookup
  (let* ((bb (make-blackboard))
         (ws (fork-workspace bb "cow"))
         (ran nil))
    (watch (workspace-blackboard ws) :id 'only-local :requires '(:t)
           :handler (lambda (board ksar)
                      (declare (ignore board ksar))
                      (setf ran t)))
    (ok (null (get-watcher bb 'only-local))
        "watcher lives on the workspace, not root")
    (write-section (workspace-blackboard ws) :t t)
    (drain bb)
    (ok ran "scheduler uses KSAR handler, not get-watcher on root")))
