(in-package #:blackboard-protocol/tests)

(deftest section-crud
  (let ((bb (make-blackboard)))
    (ok (null (read-section bb :missing)))
    (ok (eq :absent (read-section bb :missing :default :absent)))
    (ng (section-bound-p bb :missing))
    (ok (equal "hi" (write-section bb :greeting "hi")))
    (ok (section-bound-p bb :greeting))
    (ok (equal "hi" (read-section bb :greeting)))
    (ok (member :greeting (list-sections bb)))
    (remove-section bb :greeting)
    (ng (section-bound-p bb :greeting))
    (ok (eq :gone (read-section bb :greeting :default :gone)))))

(deftest write-section-change-detect
  (let ((bb (make-blackboard))
        (fires 0))
    (watch bb :id 'on-n :requires '(:n)
           :handler (lambda (board ksar)
                      (declare (ignore board ksar))
                      (incf fires)))
    (write-section bb :n 1)
    (drain bb)
    (ok (= 1 fires))
    (write-section bb :n 1)
    (drain bb)
    (ok (= 1 fires) "equal write does not re-fire")
    (write-section bb :n 2)
    (drain bb)
    (ok (= 2 fires))))

(deftest write-section-merge-fn
  (let ((bb (make-blackboard)))
    (write-section bb :nums '(1))
    (write-section bb :nums '(2) :merge-fn (lambda (old new) (append old new)))
    (ok (equal '(1 2) (read-section bb :nums)))
    (write-section bb :empty '() :merge-fn (lambda (old new)
                                            (declare (ignore old))
                                            new))
    (write-section bb :empty '(x) :merge-fn (lambda (old new) (append old new)))
    (ok (equal '(x) (read-section bb :empty))
        "merge-fn runs when the key is bound, even if old is NIL")))
