(in-package #:blackboard-protocol/tests)

(deftest watch-fires-when-requires-present
  (let ((bb (make-blackboard))
        (got nil))
    (watch bb :id 'need-ab :requires '(:a :b)
           :handler (lambda (board ksar)
                      (setf got (list (read-section board :a)
                                      (read-section board :b)
                                      (ksar-triggered-key ksar)
                                      (ksar-context ksar)))))
    (write-section bb :a 1)
    (drain bb)
    (ok (null got) "does not fire until every required key is present")
    (write-section bb :b 2)
    (drain bb)
    (ok (eql 1 (first got)))
    (ok (eql 2 (second got)))
    (ok (eq :b (third got)))
    (ok (equal '((:a . 1) (:b . 2)) (fourth got)))))

(deftest watch-already-satisfied-enqueues-initial
  (let ((bb (make-blackboard))
        (keys nil))
    (write-section bb :ready t)
    (watch bb :id 'boot :requires '(:ready)
           :handler (lambda (board ksar)
                      (declare (ignore board))
                      (push (ksar-triggered-key ksar) keys)))
    (ok (= 1 (agenda-size bb)))
    (drain bb)
    (ok (equal '(:initial) keys))))

(deftest watch-one-shot-removed-on-fire
  (let ((bb (make-blackboard))
        (n 0))
    (watch bb :id 'once :requires '(:tick) :one-shot t
           :handler (lambda (board ksar)
                      (declare (ignore board ksar))
                      (incf n)))
    (write-section bb :tick 1)
    (drain bb)
    (ok (= 1 n))
    (ok (null (get-watcher bb 'once)))
    (write-section bb :tick 2)
    (drain bb)
    (ok (= 1 n))))

(deftest watch-one-shot-already-satisfied
  (let ((bb (make-blackboard)))
    (write-section bb :go t)
    (watch bb :id 'once :requires '(:go) :one-shot t
           :handler (lambda (board ksar)
                      (declare (ignore board ksar))))
    (ok (null (get-watcher bb 'once))
        "one-shot already-satisfied watcher is removed when the initial KSAR is enqueued")
    (drain bb)))

(deftest unwatch
  (let ((bb (make-blackboard))
        (n 0))
    (watch bb :id 'w :requires '(:x)
           :handler (lambda (board ksar)
                      (declare (ignore board ksar))
                      (incf n)))
    (unwatch bb 'w)
    (write-section bb :x 1)
    (drain bb)
    (ok (= 0 n))))

(deftest handler-receives-workspace-blackboard
  (let* ((bb (make-blackboard))
         (seen nil)
         (ws (fork-workspace bb "agent")))
    (watch (workspace-blackboard ws) :id 'local :requires '(:step)
           :handler (lambda (board ksar)
                      (declare (ignore ksar))
                      (setf seen board)))
    (write-section (workspace-blackboard ws) :step 1)
    (drain bb)
    (ok (eq seen (workspace-blackboard ws))
        "handler bb is the workspace board, not root")))
