(in-package #:blackboard-protocol/tests)

(deftest cow-read-write-isolation
  (let* ((bb (make-blackboard))
         (ws (fork-workspace bb "iso")))
    (write-section bb :shared "root")
    (write-section (workspace-blackboard ws) :local "child")
    (ok (equal "root" (read-section (workspace-blackboard ws) :shared))
        "child reads parent")
    (ok (equal "child" (read-section (workspace-blackboard ws) :local)))
    (ok (eq :absent (read-section bb :local :default :absent))
        "parent does not see child override")
    (write-section (workspace-blackboard ws) :shared "shadow")
    (ok (equal "shadow" (read-section (workspace-blackboard ws) :shared)))
    (ok (equal "root" (read-section bb :shared))
        "child write does not mutate parent")))

(deftest merge-overwrite
  (let* ((bb (make-blackboard))
         (ws (fork-workspace bb "ow")))
    (write-section bb :a 1)
    (write-section bb :b 2)
    (write-section (workspace-blackboard ws) :a 9)
    (write-section (workspace-blackboard ws) :c 3)
    (merge-workspace ws :strategy :overwrite)
    (ok (eq :completed (workspace-status ws)))
    (ok (eql 9 (read-section bb :a)))
    (ok (eql 2 (read-section bb :b)))
    (ok (eql 3 (read-section bb :c)))))

(deftest merge-union
  (let* ((bb (make-blackboard))
         (ws (fork-workspace bb "un")))
    (write-section bb :keep 1)
    (write-section bb :nums '(1 2))
    (let ((ht (make-hash-table :test 'eq)))
      (setf (gethash :x ht) 1)
      (write-section bb :map ht))
    (write-section (workspace-blackboard ws) :keep 99)
    (write-section (workspace-blackboard ws) :nums '(2 3))
    (write-section (workspace-blackboard ws) :fresh :yes)
    (let ((ht (make-hash-table :test 'eq)))
      (setf (gethash :y ht) 2)
      (write-section (workspace-blackboard ws) :map ht))
    (merge-workspace ws :strategy :union)
    (ok (eql 1 (read-section bb :keep)) "scalar conflict keeps parent")
    (ok (equal '(1 2 3) (read-section bb :nums)))
    (ok (eq :yes (read-section bb :fresh)))
    (ok (eql 1 (gethash :x (read-section bb :map))))
    (ok (eql 2 (gethash :y (read-section bb :map))))))

(deftest merge-fail-on-conflict
  (let* ((bb (make-blackboard))
         (ws (fork-workspace bb "fail")))
    (write-section bb :a 1)
    (write-section (workspace-blackboard ws) :a 2)
    (write-section (workspace-blackboard ws) :b 3)
    (ok (signals (merge-workspace ws :strategy :fail-on-conflict)
                 'workspace-merge-conflict))
    (ok (eql 1 (read-section bb :a)) "parent unchanged on conflict")
    (ok (eq :absent (read-section bb :b :default :absent)))))

(deftest merge-fail-use-parent
  (let* ((bb (make-blackboard))
         (ws (fork-workspace bb "parent")))
    (write-section bb :a 1)
    (write-section (workspace-blackboard ws) :a 2)
    (write-section (workspace-blackboard ws) :b 3)
    (with-auto-use-parent
      (merge-workspace ws :strategy :fail-on-conflict))
    (ok (eql 1 (read-section bb :a)))
    (ok (eql 3 (read-section bb :b)))))

(deftest merge-fail-use-child
  (let* ((bb (make-blackboard))
         (ws (fork-workspace bb "child")))
    (write-section bb :a 1)
    (write-section (workspace-blackboard ws) :a 2)
    (with-auto-use-child
      (merge-workspace ws :strategy :fail-on-conflict))
    (ok (eql 2 (read-section bb :a)))))

(deftest merge-fail-on-conflict-ok-when-equal
  (let* ((bb (make-blackboard))
         (ws (fork-workspace bb "eq")))
    (write-section bb :a 1)
    (write-section (workspace-blackboard ws) :a 1)
    (write-section (workspace-blackboard ws) :b 2)
    (merge-workspace ws :strategy :fail-on-conflict)
    (ok (eql 1 (read-section bb :a)))
    (ok (eql 2 (read-section bb :b)))))

(deftest merge-retriggers-parent-watchers
  (let* ((bb (make-blackboard))
         (ws (fork-workspace bb "pub"))
         (n 0))
    (watch bb :id 'parent :requires '(:published)
           :handler (lambda (board ksar)
                      (declare (ignore board ksar))
                      (incf n)))
    (write-section (workspace-blackboard ws) :published t)
    (drain bb)
    (ok (= 0 n) "parent watcher does not see child override")
    (merge-workspace ws :strategy :overwrite)
    (drain bb)
    (ok (= 1 n))))

(deftest discard-reclaims-and-unregisters
  (let* ((bb (make-blackboard))
         (ws (fork-workspace bb "tmp"))
         (fired 0))
    (write-section bb :root 1)
    (write-section (workspace-blackboard ws) :secret 2)
    (watch (workspace-blackboard ws) :id 'local :requires '(:secret)
           :handler (lambda (board ksar)
                      (declare (ignore board ksar))
                      (incf fired)))
    (discard-workspace ws)
    (ok (eq :discarded (workspace-status ws)))
    (ok (null (get-workspace bb "tmp")))
    (ok (eq :absent (read-section bb :secret :default :absent)))
    (ok (null (get-watcher (workspace-blackboard ws) 'local)))
    (write-section (workspace-blackboard ws) :secret 3)
    (drain bb)
    (ok (= 0 fired) "discarded local watchers do not fire")
    (discard-workspace ws)
    (ok (eq :discarded (workspace-status ws)) "discard is idempotent")))

(deftest nested-cow-requires-use-read-path
  (let* ((bb (make-blackboard))
         (mid (fork-workspace bb "mid"))
         (leaf (fork-workspace (workspace-blackboard mid) "leaf"
                               :parent mid))
         (got nil))
    (write-section bb :from-root t)
    (write-section (workspace-blackboard mid) :from-mid t)
    (watch (workspace-blackboard leaf) :id 'nested
           :requires '(:from-root :from-mid :from-leaf)
           :handler (lambda (board ksar)
                      (setf got (list (read-section board :from-root)
                                      (read-section board :from-mid)
                                      (read-section board :from-leaf)
                                      (ksar-triggered-key ksar)))))
    (ok (= 0 (agenda-size (find-root-bb (workspace-blackboard leaf))))
        "not already satisfied — :from-leaf missing")
    (write-section (workspace-blackboard leaf) :from-leaf t)
    (drain bb)
    (ok (equal '(t t t :from-leaf) got)
        "nested requires walk the COW read path, not parent sections table")))

(deftest nested-cow-already-satisfied-via-parent-override
  (let* ((bb (make-blackboard))
         (mid (fork-workspace bb "mid"))
         (leaf (fork-workspace (workspace-blackboard mid) "leaf"))
         (key nil))
    (write-section (workspace-blackboard mid) :only-on-mid t)
    (watch (workspace-blackboard leaf) :id 'see-mid :requires '(:only-on-mid)
           :handler (lambda (board ksar)
                      (declare (ignore board))
                      (setf key (ksar-triggered-key ksar))))
    (ok (= 1 (agenda-size bb)))
    (ok (eq :initial (ksar-triggered-key (first (agenda-contents bb))))
        "already-satisfied requires must see parent COW overrides, not just root sections")
    (drain bb)
    (ok (eq :initial key))))

(deftest capabilities-shared-by-pointer
  (let* ((bb (make-blackboard))
         (cap (make-instance 'capability :name :compute))
         (ws (progn
               (register-capability bb cap)
               (fork-workspace bb "share"))))
    (ok (eq cap (get-capability (workspace-blackboard ws) :compute)))))
