(in-package #:blackboard-protocol)

(defclass workspace ()
  ((name :initarg :name :reader workspace-name)
   (parent :initarg :parent :reader workspace-parent :initform nil)
   (blackboard :initarg :blackboard :reader workspace-blackboard)
   (status :initform :active :accessor workspace-status)
   (max-steps :initarg :max-steps :reader workspace-max-steps :initform nil)
   (step-count :initform 0 :accessor workspace-step-count)))

(defclass cow-blackboard (blackboard)
  ((parent-bb :initarg :parent-bb :reader cow-parent)
   (overrides :initform (make-hash-table :test 'eq) :reader cow-overrides)
   (root-bb :initarg :root-bb :reader cow-root-bb :initform nil)))

(defmethod find-root-bb ((bb cow-blackboard))
  (or (cow-root-bb bb)
      (find-root-bb (cow-parent bb))))

(defmethod read-section ((bb cow-blackboard) key &key default)
  (bt2:with-lock-held ((blackboard-lock bb))
    (multiple-value-bind (val found) (gethash key (cow-overrides bb))
      (if found
          val
          (read-section (cow-parent bb) key :default default)))))

(defmethod section-bound-p ((bb cow-blackboard) key)
  (or (bt2:with-lock-held ((blackboard-lock bb))
        (nth-value 1 (gethash key (cow-overrides bb))))
      (section-bound-p (cow-parent bb) key)))

(defmethod write-section ((bb cow-blackboard) key value &key merge-fn)
  (let ((old nil)
        (found nil)
        (new-val nil)
        (changed-p nil))
    (bt2:with-lock-held ((blackboard-lock bb))
      (multiple-value-setq (old found) (gethash key (cow-overrides bb)))
      (setf new-val (if (and merge-fn found) (funcall merge-fn old value) value)
            changed-p (not (equal old new-val)))
      (setf (gethash key (cow-overrides bb)) new-val))
    (when changed-p
      (check-watchers-and-enqueue bb key))
    new-val))

(defmethod remove-section ((bb cow-blackboard) key)
  (bt2:with-lock-held ((blackboard-lock bb))
    (remhash key (cow-overrides bb)))
  key)

(defmethod list-sections ((bb cow-blackboard))
  (let ((keys (list-sections (cow-parent bb))))
    (bt2:with-lock-held ((blackboard-lock bb))
      (maphash (lambda (k v)
                 (declare (ignore v))
                 (pushnew k keys))
               (cow-overrides bb)))
    keys))

(defgeneric fork-workspace (bb name &key parent max-steps))
(defgeneric merge-workspace (ws &key strategy))
(defgeneric discard-workspace (ws))
(defgeneric cancel-workspace (ws &key reason))
(defgeneric list-workspaces (bb &key status))
(defgeneric get-workspace (bb name))

(defmethod fork-workspace ((bb blackboard) name &key parent max-steps)
  (let* ((root (find-root-bb bb))
         (cow (make-instance 'cow-blackboard :parent-bb bb :root-bb root
                                            :max-concurrency (blackboard-max-concurrency root)))
         (ws (make-instance 'workspace :name name :blackboard cow
                                      :parent parent :max-steps max-steps)))
    (setf (blackboard-capabilities cow) (blackboard-capabilities bb)
          (blackboard-ks-registry cow) (blackboard-ks-registry bb)
          (blackboard-owning-workspace cow) ws)
    (bt2:with-lock-held ((blackboard-lock root))
      (setf (gethash name (blackboard-workspaces root)) ws))
    ws))

(defun %union-values (parent-val child-val)
  (cond
    ((and (listp parent-val) (listp child-val)
          (not (and parent-val (symbolp (first parent-val))
                    (char= #\: (char (symbol-name (first parent-val)) 0)))))
     (append parent-val (remove-if (lambda (x) (member x parent-val :test #'equal))
                                   child-val)))
    ((and (hash-table-p parent-val) (hash-table-p child-val))
     (let ((out (make-hash-table :test (hash-table-test parent-val))))
       (maphash (lambda (k v) (setf (gethash k out) v)) parent-val)
       (maphash (lambda (k v) (setf (gethash k out) v)) child-val)
       out))
    (t parent-val)))

(defun %merge-pairs (ws strategy)
  (let* ((cow (workspace-blackboard ws))
         (parent (cow-parent cow))
         (pairs nil))
    (bt2:with-lock-held ((blackboard-lock cow))
      (maphash (lambda (k v) (push (cons k v) pairs))
               (cow-overrides cow)))
    (ecase strategy
      (:overwrite
       (dolist (pair (nreverse pairs))
         (write-section parent (car pair) (cdr pair))))
      (:union
       (dolist (pair (nreverse pairs))
         (let ((key (car pair))
               (child (cdr pair)))
           (if (section-bound-p parent key)
               (let ((pv (read-section parent key)))
                 (unless (equal pv child)
                   (write-section parent key (%union-values pv child))))
               (write-section parent key child)))))
      (:fail-on-conflict
       (let ((resolved nil))
         (dolist (pair pairs)
           (let* ((key (car pair))
                  (child (cdr pair))
                  (parent-val (and (section-bound-p parent key)
                                   (read-section parent key))))
             (if (and (section-bound-p parent key)
                      (not (equal parent-val child)))
                 (let ((decision
                        (restart-case
                            (error 'workspace-merge-conflict
                                   :key key
                                   :parent-value parent-val
                                   :child-value child)
                          (use-parent ()
                            :report "Keep the parent value"
                            :parent)
                          (use-child ()
                            :report "Overwrite with the child value"
                            :child)
                          (use-value (value)
                            :report "Use a supplied section value"
                            (cons :value value)))))
                   (push (list key child decision) resolved))
                 (push (list key child (cons :value child)) resolved))))
         (dolist (item (nreverse resolved))
           (destructuring-bind (key child decision) item
             (let ((value (cond
                            ((eq decision :parent) nil)
                            ((eq decision :child) child)
                            ((and (consp decision) (eq (car decision) :value))
                             (cdr decision))
                            (t child))))
               (when (and (not (eq decision :parent))
                          (not (and (section-bound-p parent key)
                                    (equal (read-section parent key) value))))
                 (write-section parent key value))))))))
    ws))

(defmethod merge-workspace ((ws workspace) &key (strategy :overwrite))
  (let ((cow (workspace-blackboard ws)))
    (unless (typep cow 'cow-blackboard)
      (error 'workspace-error :message "not a COW workspace"))
    (%merge-pairs ws strategy)
    (setf (workspace-status ws) :completed)
    ws))

(defmethod discard-workspace ((ws workspace))
  (let* ((cow (workspace-blackboard ws))
         (root (find-root-bb cow)))
    (when (typep cow 'cow-blackboard)
      (bt2:with-lock-held ((blackboard-lock cow))
        (clrhash (cow-overrides cow)))
      (bt2:with-lock-held ((bb-watchers-lock cow))
        (clrhash (bb-watchers cow))
        (setf (bb-watchers-order cow) nil)))
    (bt2:with-lock-held ((blackboard-lock root))
      (remhash (workspace-name ws) (blackboard-workspaces root)))
    (setf (workspace-status ws) :discarded)
    ws))

(defmethod cancel-workspace ((ws workspace) &key reason)
  (declare (ignore reason))
  (setf (workspace-status ws) :cancelled)
  (let ((root (find-root-bb (workspace-blackboard ws))))
    (bt2:with-lock-held ((bb-agenda-lock root))
      (pqueue-delete-if (bb-agenda root)
                        (lambda (ksar)
                          (eq (ksar-workspace ksar) ws)))
      (bt2:condition-notify (bb-agenda-cv root))))
  ws)

(defmethod list-workspaces ((bb blackboard) &key status)
  (let ((root (find-root-bb bb)))
    (bt2:with-lock-held ((blackboard-lock root))
      (loop for ws being the hash-values of (blackboard-workspaces root)
            when (or (null status) (eq (workspace-status ws) status))
              collect ws))))

(defmethod get-workspace ((bb blackboard) name)
  (let ((root (find-root-bb bb)))
    (bt2:with-lock-held ((blackboard-lock root))
      (gethash name (blackboard-workspaces root)))))
